apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root
  namespace: cert-manager
spec:
  isCA: true
  duration: 262980h #30 years
  renewBefore: 17532h #2 years
  commonName: Root
  secretName: root-keypair
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - crl sign
    - cert sign
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-issuer
spec:
  ca:
    secretName: root-keypair
