apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hono-ca
  namespace: hono
spec:
  isCA: true
  duration: 8766h #1 year
  renewBefore: 730h #1 month
  commonName: Hono CA
  secretName: hono-ca-keypair
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - crl sign
    - cert sign
  issuerRef:
    name: root-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "cert-manager"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "cert-manager"

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: hono-ca-issuer
  namespace: hono
spec:
  ca:
    secretName: hono-ca-keypair
